class ApiData {
  List Data() {
    return [
      // images/img1.jpg
      {'section_name': "Meats",
        'section_image':"images/img4.jpeg",
       'info_products': ["Chiken","Meats","Camel Meats"],
       'info_images': ["images/img4_chiken.jpg","images/img4.jpeg","images/img4_camelmeats.jpg"],
       'info_prices':[30,25,35]},
      {'section_name': "Juice",
        'section_image':"images/img3.jpg",
       'info_products': ["Apple","Orange","Lemon"],
       'info_images': ["images/img3.jpg","images/img3.jpg","images/img3.jpg"],
       'info_prices':[10,15,10]},
      {'section_name': "Chocolate",
        'section_image':"images/img10.jpg",
       'info_products': ["Chocolate","Vanelia"],
       'info_images': ["images/img10.jpg","images/img10.jpg"],
       'info_prices':[35,35]},
      {'section_name': "Cold Drinks",
        'section_image':"images/img5.jpg",
       'info_products': ["Cola","Orange Pepsi"],
       'info_images': ["images/img5.jpg","images/img5.jpg"],
       'info_prices':[15,15]},
      {'section_name': "Pasta",
        'section_image':"images/img6.webp",
       'info_products': ["Pasta","Pasta & Bashamil"],
       'info_images': ["images/img6.webp","images/img6.webp"],
       'info_prices':[30,25]},
      {'section_name': "Friuts",
        'section_image':"images/img8.webp",
       'info_products': ["Apple","Orange","Mango"],
       'info_images': ["images/img8.webp","images/img8.webp","images/img8.webp"],
       'info_prices':[10,15,20]},
      {'section_name': "Vegitables",
        'section_image':"images/img7.webp",
       'info_products': ["cucumber","Carrots"],
       'info_images': ["images/img7.webp","images/img7.webp"],
       'info_prices':[5,5]},
      {'section_name': "Legumes",
        'section_image':"images/img9.webp",
       'info_products': ["lentils","kidney bean","Bean","Peanut","peas"],
       'info_images': ["images/img9.webp","images/img9.webp","images/img9.webp","images/img9.webp","images/img9.webp"],
       'info_prices':[10,15,10,20,20]},
      {'section_name': "Friuts",
        'section_image':"images/img8.webp",
       'info_products': ["Apple","Orange","Mango"],
       'info_images': ["images/img8.webp","images/img8.webp","images/img8.webp"],
       'info_prices':[10,15,20]},
      {'section_name': "Vegitables",
        'section_image':"images/img7.webp",
       'info_products': ["cucumber","Carrots"],
       'info_images': ["images/img7.webp","images/img7.webp"],
       'info_prices':[5,5]},
    ];
  }
}
